// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnicRjGl1ThJ8q6Dzh4gREFgk9lFgdqiw',
    appId: '1:707473240457:web:5edc5efb532b5135993158',
    messagingSenderId: '707473240457',
    projectId: 'fruithup-app',
    authDomain: 'fruithup-app.firebaseapp.com',
    storageBucket: 'fruithup-app.firebasestorage.app',
    measurementId: 'G-VSKG6HVRLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb0p07cEDrWDkTA4FX9G0_bzYKxu9HY3w',
    appId: '1:707473240457:android:157b06aa6c3ae7f2993158',
    messagingSenderId: '707473240457',
    projectId: 'fruithup-app',
    storageBucket: 'fruithup-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ4Hxtj8suRcQ0mOkQnxiLInVY0dk8Btg',
    appId: '1:707473240457:ios:8bb1d2ad6be381e1993158',
    messagingSenderId: '707473240457',
    projectId: 'fruithup-app',
    storageBucket: 'fruithup-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ4Hxtj8suRcQ0mOkQnxiLInVY0dk8Btg',
    appId: '1:707473240457:ios:8bb1d2ad6be381e1993158',
    messagingSenderId: '707473240457',
    projectId: 'fruithup-app',
    storageBucket: 'fruithup-app.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnicRjGl1ThJ8q6Dzh4gREFgk9lFgdqiw',
    appId: '1:707473240457:web:8301e039c07f35c1993158',
    messagingSenderId: '707473240457',
    projectId: 'fruithup-app',
    authDomain: 'fruithup-app.firebaseapp.com',
    storageBucket: 'fruithup-app.firebasestorage.app',
    measurementId: 'G-GY2Q525XWB',
  );
}
